# Generated by Django 3.2.18 on 2023-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('calicut', 'CALICUT'), ('kannur', 'KANNUR'), ('ernakulam', 'ERNAKULAM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
