# Generated by Django 3.2.18 on 2023-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_auto_20230221_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='branch',
            field=models.CharField(blank=True, choices=[('option1-1', 'Thamarassery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('option1', 'CALICUT'), ('option2', 'KANNUR'), ('option3', 'ERNAKULAM')], max_length=20, null=True),
        ),
    ]
