# Generated by Django 3.2.18 on 2023-02-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_auto_20230221_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('calicut', 'CALICUT'), ('option2', 'KANNUR'), ('option3', 'ERNAKULAM')], max_length=20, null=True),
        ),
    ]
