# Generated by Django 3.2.18 on 2023-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_alter_detail_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='branch',
        ),
        migrations.AddField(
            model_name='detail',
            name='account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('option1', 'CALICUT'), ('option2', 'KANNUR'), ('option3', 'ERNAKULAM'), ('option4', 'Malappuram'), ('option5', 'Palakkad')], max_length=20, null=True),
        ),
    ]
