# Generated by Django 3.2.18 on 2023-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0005_auto_20230222_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='materials',
            field=models.CharField(blank=True, choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card'), ('Cheque book', 'Cheque book')], max_length=20, null=True),
        ),
    ]
