# Generated by Django 3.2.18 on 2023-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0008_detail_subd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('option1', 'calicut'), ('option2', 'Kannur'), ('option3', 'Ernakulam'), ('option4', 'Malappuram'), ('option5', 'Palakkad')], max_length=20, null=True),
        ),
    ]
