# Generated by Django 3.2.18 on 2023-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0011_alter_detail_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='materials',
            field=models.CharField(blank=True, choices=[('debitcard', 'Debit card'), ('creditcard', 'Credit card'), ('cheque', 'Cheque book')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='subd',
            field=models.CharField(blank=True, choices=[('option1-1', 'Thamarassery'), ('option1-2', 'Koyilandi'), ('option1-3', 'Beypur'), ('option1-4', 'Vadakara'), ('option2-1', 'Thalassery'), ('option2-2', 'Iritti'), ('option2-3', 'Payyanur'), ('option2-4', 'Thaliparamba'), ('option2-1', 'Cochin'), ('option2-2', 'Aluva'), ('option2-3', 'Edappalli'), ('option2-4', 'Vypin'), ('option2-1', 'Eranad'), ('option2-2', 'Kondotti'), ('option2-3', 'Nilambur'), ('option2-4', 'Ponnani')], max_length=20, null=True),
        ),
    ]
