# Generated by Django 3.2.18 on 2023-02-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0013_alter_detail_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='subd',
            field=models.CharField(blank=True, choices=[('option1-1', 'Thamarassery'), ('option1-2', 'Koyilandi'), ('option1-3', 'Beypur'), ('option1-4', 'Vadakara'), ('option2-1', 'Thalassery'), ('option2-2', 'Iritti'), ('option2-3', 'Payyanur'), ('option2-4', 'Thaliparamba'), ('option3-1', 'Cochin'), ('option3-2', 'Aluva'), ('option3-3', 'Edappalli'), ('option3-4', 'Vypin'), ('option4-1', 'Eranad'), ('option4-2', 'Kondotti'), ('option4-3', 'Nilambur'), ('option4-4', 'Ponnani')], max_length=20, null=True),
        ),
    ]
