# Generated by Django 3.2.18 on 2023-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0014_alter_detail_subd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='district',
            field=models.CharField(blank=True, choices=[('option1', 'Calicut'), ('option2', 'Kannur'), ('option3', 'Ernakulam'), ('option4', 'Malappuram'), ('option5', 'Palakkad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='subd',
            field=models.CharField(blank=True, choices=[('option1-1', 'Thamarassery'), ('option1-2', 'Koyilandi'), ('option1-3', 'Beypur'), ('option1-4', 'Vadakara'), ('option2-1', 'Thalassery'), ('option2-2', 'Iritti'), ('option2-3', 'Payyanur'), ('option2-4', 'Thaliparamba'), ('option3-1', 'Cochin'), ('option3-2', 'Aluva'), ('option3-3', 'Edappalli'), ('option3-4', 'Vypin'), ('option4-1', 'Eranad'), ('option4-2', 'Kondotti'), ('option4-3', 'Nilambur'), ('option4-4', 'Ponnani'), ('option5-1', 'Chittur'), ('option5-2', 'Ottapalam'), ('option5-3', 'Mannarkad'), ('option5-4', 'Pattambi')], max_length=20, null=True),
        ),
    ]
