# Generated by Django 3.2.18 on 2023-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0015_auto_20230223_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1, null=True),
        ),
    ]
